---
title: 使用R / Bioconductor分析单细胞RNA-seq数据的工作流程
author: 
- name: Aaron T. L. Lun
  affiliation: &CRUK Cancer Research UK Cambridge Institute, Li Ka Shing Centre, Robinson Way, Cambridge CB2 0RE, United Kingdom
- name: Davis J. McCarthy
  affiliation: 
  - &EMBL EMBL European Bioinformatics Institute, Wellcome Genome Campus, Hinxton, Cambridge CB10 1SD, United Kingdom
  - St Vincent's Institute of Medical Research, 41 Victoria Parade, Fitzroy, Victoria 3065, Australia
- name: John C. Marioni
  affiliation: 
  - *CRUK
  - *EMBL
  - Wellcome Trust Sanger Institute, Wellcome Genome Campus, Hinxton, Cambridge CB10 1SA, United Kingdom
date: "`r Sys.Date()`"
vignette: >
  %\VignetteIndexEntry{01. Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}    
output: 
  BiocStyle::html_document:
    toc_float: true
bibliography: ref.bib
---

```{r style, echo=FALSE, results='hide', message=FALSE, cache=FALSE}
library(BiocStyle)
library(knitr)
opts_chunk$set(error=FALSE, message=FALSE, warning=FALSE, cache=TRUE)
```

# 分析流程版本信息

**R 版本**: `r R.version.string`

**Bioconductor 版本**: `r BiocManager::version()`

**该R包版本**: `r packageVersion("simpleSingleCell")`

# 动机

单细胞RNA测序（scRNA-seq）b被广泛用于测量单个细胞的全基因组表达状况。
从每个细胞中分离mRNA并将其逆转录为cDNA以进行高通量测序 [@stegle2015computational].
测序的方法可以使用微流体平台，如Fluidigm C1 [@pollen2014lowcoverage], 基于微量滴定板的方案，如Smart-seq2  [@picelli2014fulllength], 或基于液滴的技术，如inDrop [@klein2015droplet;@macosko2015highly]。
然后使用比对到每个基因的read的数量来量化其在每个细胞中的表达量。又或者，独特的分子标识物（UMI）可用于直接测量每个基因的转录物分子数 [@islam2014quantitative]。
分析单细胞转录组计数数据来检测高度多变的基因（HVG），这些高度多变的基因能驱动群体中细胞的异质性。分析单细胞转录组数据也能发现基因和细胞表型之间的相关性，或通过降维和聚类来鉴定新的亚群。这能让我们从单细胞水平去理解生物学问题，这是细胞群水平的传统的RNA测序无法实现的。

scRNA-seq数据分析的策略与传统的RNA-seq的策略明显不同。
其一个技术原因是scRNA-seq数据比传统批量数据噪声更大 [@brennecke2013accounting;@marinov2014singlecell]。
由于单个细胞中RNA的量低，难以将转录物可靠地捕获（即转化）成cDNA用于测序。
这增加了drop-out事件的频率，并产生没有捕获基因的转录物。在分析过程中需要专门的步骤来处理这种噪音，特别是在质控的时候。此外，scRNA-seq数据可用于研究细胞间异质性，例如，识别新的细胞亚型，表征分化过程，将细胞分配到细胞周期阶段，或识别驱动整个种群的变异性的高度多变基因(HVG) [@vallejos2015basics;@fan2016characterizing;@trapnell2014dynamics]。
传统的批量RNA数据并不能实现上面提到的应用，这意味着需要新的分析流程来执行单细胞转录组分析。

# 使用Bioconductor 进行单细胞数据分析

该软件包包含一组用于scRNA-seq基本数据分析的计算工作流程，使用来自开源Bioconductor项目的软件 [@huber2015orchestrating].
工作流程从计数矩阵开始，描述了一系列scRNA-seq数据分析的关键步骤，包括：

- 质控，以消除有问题的细胞;
- 细胞特异性偏倚的正常化, 有还是没有标记; 
- 批量效应的修正; 
- 基因表达数据的细胞周期阶段分类; 
- 数据探索，以确定推定的亚群; 
- 最后，HVG和标记基因的识别以确认感兴趣的基因。

几个公共scRNA-seq数据集将用于展示该工具的分析流程，这些数据集包括永生化骨髓祖细胞，脑细胞，造血干细胞，T辅助细胞和小鼠胚胎干细胞。 这些数据集都是通过一系列实验方案和平台生成。 [@lun2017assessing;@wilson2015combined;@zeisel2015brain;@islam2011characterization;@buettner2015computational;@zheng2017massively].
z这样做的目的是提供各种模块化使用示例，以便读者可以更好的使用这些示例来为自己的实验构建自定义分析流程。

请参阅 `r Biocpkg("simpleSingleCell")` 登录页面，以获取各个工作流程的链接以及有关如何安装所需软件包的说明。要引用任何这些工作流程，请参阅 http://f1000research.com/articles/5-2122/v2 以获取相关说明。

# 获取计数矩阵

所有这些工作流程都从公开可用的计数矩阵开始。
为简单起见，我们放弃了生成计数矩阵所需的读取处理步骤的描述，即read的比对和其相关特征的统计。
对于SMART-seq2数据 [@picelli2014fulllength], 针对大量RNA-seq开发的定量程序通常是令人满意的 [@love2015rnaseq;@chen2016from].
喜欢使用基于R的方法来进行read的比对和计数的用户可以考虑使用 `r Biocpkg("Rsubread")` 包中的方法 [@liao2013subread;@liao2014featurecounts]。

许多其它scRNA-seq实验方法都包含需要小心处理的预定的序列结构：

- 独特的分子标识物 (UMIs) [@islam2014quantitative] 被广泛用于减轻扩增偏差的影响。
具有相同的UMI比对到相同基因的reads代表单个基础转录物分子并且仅将该基因的计数增加1。
处理此数据需要从每个read或reads对中提取UMI序列，以及将基于UMI的重复项整合为单个计数的方法 [@smith2017umitools]。
- 有些方法还可以使用定制细胞条形码来提高多路复用效率，以超过标准测序条形码的效率（例如，来自Illumina）。
这包括基于液滴的实验， [@zheng2017massively] 或非常高通量的基于板的实验技术（如MARS-seq)生成的数据。 [@jaitin2014massively]。
处理该数据通常需要单独的步骤，从每次read中提取条形码序列并将read，并准确地分配给每个细胞的测序文库。

对于这些数据集,`r Biocpkg("scPipe")` 包 [@lian2018scpipe] p）提供了用于获得计数矩阵的基于R的处理流程。

如果添加加标RNA，则在比对之前的基因组索引构建期间可以将包括加标转录物的序列作为额外的FASTA文件。
类似地，可以在计数之前将加标转录物和内源基因的基因组间隔连接成单个GTF文件。

# Author information

## Author contributions

A.T.L.L. developed and tested workflows on all datasets.
A.T.L.L. and D.J.M. implemented improvements to the software packages required by the workflow.
J.C.M. provided direction to the software and workflow development.
All authors wrote and approved the final manuscript.

## Competing interests

No competing interests were disclosed.

## Grant information

A.T.L.L. and J.C.M. were supported by core funding from Cancer Research UK (award no. A17197).
D.J.M. was supported by a CJ Martin Fellowship from the National Health and Medical Research Council of Australia.
D.J.M and J.C.M. were also supported by core funding from EMBL.

## Acknowledgements

We would like to thank Antonio Scialdone for helpful discussions, as well as Michael Epstein, James R. Smith and John Wilson-Kanamori for testing the workflow on other datasets.

# References

